spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5433/polaris_inventory
    username: polaris_inventory
    password: polaris_inventory
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

polaris:
  inventory:
    grpc:
      port: 9090
  kafka:
    topics:
      orders-created: polaris.orders.created
      inventory-adjusted: polaris.inventory.adjusted

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://inventory-postgres:5432/polaris_inventory
  kafka:
    bootstrap-servers: kafka:9092
